package com.atrvasa.infra.service;

import com.atrvasa.infra.StringTools;

import java.util.UUID;

/**
 * this class contain session data of logged in user
 */
public class SessionModel {
    /**
     * username equals username in user model
     */
    private String username;
    /**
     * cultureName selected by user when logged in
     */
    private String cultureName;
    /**
     * sessionId generated by users-mgr for each user that
     * successfully logged in.
     */
    private String sessionId;
    /**
     * when user lock screen and need to put password to continue
     * to woek
     */
    private boolean lock;
    /**
     * userFullName comes from user profile to show in dashboard, report
     * and other place to needs
     */
    private String userFullName;
    /**
     * when user depend to organization and select any one in login form
     * the organizational id saved here for attach to any jobs user done.
     */
    private UUID userOrganization;



    public SessionModel() {
    }

    public SessionModel(String username, String userFullName, String cultureName, String sessionId, boolean lock, UUID organization) {
        this.username = username;
        this.userFullName = userFullName;
        this.cultureName = cultureName;
        this.sessionId = sessionId;
        this.lock = lock;
        this.userOrganization = organization;
    }

    //region GETTER & SETTER

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getCultureName() {
        return cultureName;
    }

    public void setCultureName(String cultureName) {
        this.cultureName = cultureName;
    }

    public String getSessionId() {
        return sessionId;
    }

    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }

    public boolean isLock() {
        return lock;
    }

    public void setLock(boolean lock) {
        this.lock = lock;
    }

    public String getUserFullName() {
        return userFullName;
    }

    public void setUserFullName(String userFullName) {
        this.userFullName = userFullName;
    }

    public UUID getUserOrganization() {
        return userOrganization;
    }

    public void setUserOrganization(UUID userOrganization) {
        this.userOrganization = userOrganization;
    }

    //endregion


    /**
     * getUserTitle return value of String
     * if user has user full name in user profile
     * return user full name otherwise return username
     *
     * @return String username or user full name
     */
    public String getUserTitle(){
        if(StringTools.isNullOrEmpty(this.userFullName))
            return this.username;
        else
            return this.userFullName;
    }


    @Override
    public String toString() {
        return "SessionModel{" +
                "username='" + username + '\'' +
                ", cultureName='" + cultureName + '\'' +
                ", userOrganization=" + userOrganization +
                '}';
    }
}
